myblog/blog/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url   # 此句是配置url必需
from  . import views
# urls 是配置路由的地方
urlpatterns = [
    url(r'^index/$', views.index),
    # ^表示开头，$表示结尾 【正则表达式】 ^$表示约束空字符 否则localhost:8000/index/.....都可以访问到此
    # 坑：url(r'^index$', views.index),   正确：url(r'^index/$', views.index),
    url(r'^article/(?P<article_id>[0-9]+)$', views.article_page, name='article_page')
    # (?P<article_id>[0-9]+) 组名
    # name='变量' 传递给
]

myblog/blog2/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url   # 此句是配置url必需
from  . import views
# urls 是配置路由的地方
urlpatterns = [
    url(r'^index/$', views.index),
    # ^表示开头，$表示结尾 【正则表达式】 ^$表示约束空字符 否则localhost:8000/index/.....都可以访问到此
    # 坑：url(r'^index$', views.index),   正确：url(r'^index/$', views.index),
]

myblog/myblog/urls.py
# -*- coding:utf-8 -*-
"""myblog URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
import blog.views as bv
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),  # blog为应用  urls为blog下的路由 相当于二级路由
    url(r'^blog2/', include('blog2.urls'))
    # index总路径
    # 引用应用blog下的urls 防止过多文件积聚
]

myblog/blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# 操作数据库相关models
# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=32, default='Title' )  # max_length=必须有
    content =  models.TextField(null=True)  # 允许为空
    def __unicode__(self):
        return self.title  # 使后台显示标题

myblog/blog2/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

myblog/blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

'''
    Django是MVT的模式
    M:  models.py 负责操作数据库相关
    V:  views.py 负责controller的任务 即收到前端数据 -》编写对应操作-》传至前端 起java中Servlet的作用 控制器
    T:  templates 模板 即前端展示 也可以理解为mvc模式中的view 即展示界面
'''


from django.shortcuts import render     # 生成应用时自动添加  render 渲染的意思
from django.http import HttpResponse

from . import models

def index(request):
    # return  HttpResponse('Hello,World!')
    articles = models.Article.objects.all()#.get(pk=1)  # all()查询返回的就是一个列表
    return render(request, 'blog/index.html',{'articles':articles})  # 传到前台  之后注意编写前台代码
    # return render(request,'blog/index.html')   #,{'hello':'Hello,Blog!瞎写的'})
# render(request, 模板文件， 传递到前台的数据)  # 模板

def article_page(request, article_id):  # 在url中奋发又怎么体现呢
    '''
    响应前端函数
    :param request:
    :return:
    '''
    article = models.Article.objects.get(pk=article_id)   # 传什么参数？  前端是点击主页面的超链接进来的
    # 拿到点击文章的唯一标示：主键  修改views.py  参数 来传递关键参数
    # 最后渲染到模板里
    return render(request, 'blog/article_page.html', {'article':article})  # 渲染到模板







myblog/blog2/views.py
# -*- coding: utf-8 -*-
# from __future__ import unicode_literals  # 必须出现在文件的开头

from django.shortcuts import render     # 生成应用时自动添加  render 渲染的意思
from django.http import HttpResponse

def index(request):
    # return  HttpResponse('Hello,World!')
    return render(request,'blog2/index.html')   #,{'hello':'Hello,Blog!瞎写的'})
# render(request, 模板文件， 传递到前台的数据)  # 模板
# Create your views here.

# Create your views here.

myblog/blog/templates/blog/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Article Page</title>
</head>
<body>
    <h1>{{ article.title }}</h1>
    <br />
<h3>{{ article.content }}</h3>
<br /><br />
<a href="">修改文章</a>
</body>
</html>

myblog/blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!--    <h1>Hello,Blog!</h1>-->
<h1>
    <a href="">新文章</a>
</h1>
{% for article in articles %}<!--{'articles':articles}  for 循环中的articles 是dict中的键-->
    <a href="{% url 'blog:article_page' article.id %}"> {{ article.title }} <br /></a>

<!--  url 'app_name:url_name' param -->
<!--    <h3>{{ i.content}}</h3>-->
{% endfor %}

<!--只有一个数据时

    <h1>{{ article.title }}</h1>
    <h3>{{ article.content}}</h3>
-->
</body>
</html>

myblog/blog2/templates/blog2/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Hello,Blog2!</h1>
    <!--<h1>{{ hello }}</h1>-->
</body>
</html>